In [3]:
import numpy as np
import pandas as pd

In [4]:
import json
with open('response_2024-02-07.json', 'r') as file:
    data = json.load(file)

In [5]:
df = pd.DataFrame()
for x in range(0, len(data['data'])):
    curr = data["data"][x]

    for i in range(0, len(curr['home_team']['players'])):
        flat_data = {
            **curr,
            **{f"homeTeam_{k}": v for k, v in curr['home_team'].items() if k != 'players'},
            **curr['home_team']['players'][i],
            **{f"homeTeamPlayer_{k}": v for k, v in curr['home_team']['players'][i]['player'].items()},
        }
        df = pd.concat([df, pd.DataFrame([flat_data])])
    for j in range(0, len(curr['visitor_team']['players'])):
        flat_data_visit = {
            **curr,
            **{f"visitorTeam_{k}": v for k, v in curr['visitor_team'].items() if k != 'players'},
            **curr['visitor_team']['players'][j],
            **{f"visitorTeamPlayer_{k}": v for k, v in curr['visitor_team']['players'][j]['player'].items()},
        }
        df = pd.concat([df, pd.DataFrame([flat_data_visit])])

In [6]:
df

,date,season,status,period,time,postseason,home_team_score,visitor_team_score,home_team,visitor_team,...,visitorTeamPlayer_last_name,visitorTeamPlayer_position,visitorTeamPlayer_height,visitorTeamPlayer_weight,visitorTeamPlayer_jersey_number,visitorTeamPlayer_college,visitorTeamPlayer_country,visitorTeamPlayer_draft_year,visitorTeamPlayer_draft_round,visitorTeamPlayer_draft_number
0,2024-02-07,2023,Final,4,Final,False,117,123,"{'id': 4, 'conference': 'East', 'division': 'S...","{'id': 28, 'conference': 'East', 'division': '...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2024-02-07,2023,Final,4,Final,False,117,123,"{'id': 4, 'conference': 'East', 'division': 'S...","{'id': 28, 'conference': 'East', 'division': '...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2024-02-07,2023,Final,4,Final,False,117,123,"{'id': 4, 'conference': 'East', 'division': 'S...","{'id': 28, 'conference': 'East', 'division': '...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2024-02-07,2023,Final,4,Final,False,117,123,"{'id': 4, 'conference': 'East', 'division': 'S...","{'id': 28, 'conference': 'East', 'division': '...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2024-02-07,2023,Final,4,Final,False,117,123,"{'id': 4, 'conference': 'East', 'division': 'S...","{'id': 28, 'conference': 'East', 'division': '...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2024-02-07,2023,Final,4,Final,False,120,133,"{'id': 26, 'conference': 'West', 'division': '...","{'id': 9, 'conference': 'East', 'division': 'C...",...,Bogdanovic,F,6-7,226,44,Fenerbahce,Croatia,2011.0,2.0,31.0
0,2024-02-07,2023,Final,4,Final,False,120,133,"{'id': 26, 'conference': 'West', 'division': '...","{'id': 9, 'conference': 'East', 'division': 'C...",...,Burks,G,6-5,214,18,Colorado,USA,2011.0,1.0,12.0
0,2024-02-07,2023,Final,4,Final,False,120,133,"{'id': 26, 'conference': 'West', 'division': '...","{'id': 9, 'conference': 'East', 'division': 'C...",...,Cunningham,G-F,6-6,220,2,Oklahoma State,USA,2021.0,1.0,1.0
0,2024-02-07,2023,Final,4,Final,False,120,133,"{'id': 26, 'conference': 'West', 'division': '...","{'id': 9, 'conference': 'East', 'division': 'C...",...,Gallinari,F,6-10,236,12,Olimpia Milano,Italy,2008.0,1.0,6.0
0,2024-02-07,2023,Final,4,Final,False,120,133,"{'id': 26, 'conference': 'West', 'division': '...","{'id': 9, 'conference': 'East', 'division': 'C...",...,Harris,F-G,6-6,220,12,Virginia,USA,2014.0,2.0,33.0